### ISSUE TITLE
Sitemap shows Uncaught Error: Call to undefined function wc_get_page_id()

### ISSUE THREAD

**Issue by amboutwe** [Yoast/wpseo-woocommerce#327]
### Please give us a description of what happened.
Sitemap returns an error. Stack trace below.

`Fatal error: Uncaught Error: Call to undefined function wc_get_page_id() in /PATH_TO_WORDPRESS/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php:307`

### Please describe what you expected to happen and why.
Sitemap would load without error.

### How can we reproduce this behavior?
1. Install and activate Yoast SEO and Yoast SEO: WooCommerce
2. Load post or page sitemap
3. See error.

### Used versions
* WordPress version: 5.1
* Yoast SEO version: 9.7
* Yoast SEO add-on version: 9.7
* Tested with theme: Twenty Nineteen
* Regression: No. Happens with 9.6.1

### Workaround
Disable Yoast SEO: WooCommerce or install WooCommerce

### Full error
```
Fatal error: Uncaught Error: Call to undefined function wc_get_page_id() in /PATH_TO_WORDPRESS/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php:307

Stack trace:
#0 /PATH_TO_WORDPRESS/wp-includes/class-wp-hook.php(286): Yoast_WooCommerce_SEO->filter_woocommerce_pages(Array)
#1 /PATH_TO_WORDPRESS/wp-includes/plugin.php(208): WP_Hook->apply_filters(Array, Array)
#2 /PATH_TO_WORDPRESS/wp-content/plugins/wordpress-seo-premium/inc/sitemaps/class-post-type-sitemap-provider.php(346): apply_filters('wpseo_exclude_f...', Array)
#3 /PATH_TO_WORDPRESS/wp-content/plugins/wordpress-seo-premium/inc/sitemaps/class-post-type-sitemap-provider.php(242): WPSEO_Post_Type_Sitemap_Provider->get_excluded_posts('page')
#4 /PATH_TO_WORDPRESS/wp-content/plugins/wordpress-seo-premium/inc/sitemaps/class-sitemaps.php(351): WPSEO_Post_Type_Sitemap_Provider->get_sitemap_links('page', 1000, 1)
#5 /PATH_TO_WORDPRESS/wp-content/plugins/wordpress-seo-premium/inc/sitemaps/class-s in /PATH_TO_WORDPRESS/wp-content/plugins/wpseo-woocommerce/wpseo-woocommerce.php on line 307
```

**Comment by moorscode** [comment]
We want to avoid throwing fatal errors in all cases, so this needs to be avoided.
The WooCommerce SEO functionality for sitemaps should not be loaded when WooCommerce is not activated.

**Comment by benvaassen** [comment]
Please inform the customer of conversation # 479105 when this conversation has been closed.
