### ISSUE TITLE
No notification to upgrade add on

### ISSUE THREAD

**Issue by dariaknl** [Yoast/wpseo-woocommerce#565]
### How can we reproduce this behavior?
1. Install and activate SEO Woo 12.7.
2. Install and activate Yoast SEO 14.0.
See that you see no notification/warning for SEO Woo.
3. Go to create new post, browse to post - then you get
`Fatal error: Uncaught TypeError: Argument 1 passed to WPSEO_WooCommerce_OpenGraph::set_opengraph_image() must be an instance of WPSEO_OpenGraph_Image, instance of Yoast\WP\SEO\Values\Open_Graph\Images given, called in /srv/www/local/public_html/wp-includes/class-wp-hook.php on line 287 and defined in /srv/www/local/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-opengraph.php:97 Stack trace: #0 /srv/www/local/public_html/wp-includes/class-wp-hook.php(287): WPSEO_WooCommerce_OpenGraph->set_opengraph_image(Object(Yoast\WP\SEO\Values\Open_Graph\Images)) #1 /srv/www/local/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /srv/www/local/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /srv/www/local/public_html/wp-content/plugins/wordpress-seo/src/generators/open-graph-image-generator.php(98): do_action('wpseo_add_openg...', Object(Yoast\WP\SEO\Values\Open_Graph\Images)) #4 /srv/www/local/public_html/wp-content/plugins/wordpress-seo/src/presentations/ in /srv/www/local/public_html/wp-content/plugins/wpseo-woocommerce/classes/woocommerce-opengraph.php on line 97`

I would expect warning that I need to upgrade my SEO Woo to 13.0 after activation of Yoast SEO 14.0.

### Technical info
* WordPress version: 5.4
* Yoast SEO version: 14.0
* Yoast SEO for WooCommerce version:

**Comment by dariaknl** [comment]
opened in https://github.com/Yoast/wordpress-seo/issues/14689
